# Generated by Django 4.1.4 on 2022-12-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_about_client_recentwork_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('technology', models.CharField(max_length=255)),
                ('project', models.DateTimeField()),
                ('github_url', models.CharField(max_length=255)),
            ],
        ),
    ]
